apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-passwd
  namespace: iot-stack
data:
  passwd: |
    ZXNwMzI6JDckMTAxJFF6QzNMOGV5LzF0dEhkNHIkUStjZ1pabnFhY2UxeTNTNHRvbHRZc05uWUhH
    UmpGc3N2OFRsY2pYSTZqWDBLVFZzU3hqb3d6aHh3eHh2VTlHNWF4ckd3QVoxa0hkd2hGcExTZEFG
    NkE9PQo=